@endpoint = http://localhost:7071
@auth = token

### Get list of games
GET {{endpoint}}/api/games HTTP/1.1
Content-type: application/json
X-MyChessAuth: Bearer {{auth}}

### Get single game
GET {{endpoint}}/api/games/123-abc-123 HTTP/1.1
Content-type: application/json
X-MyChessAuth: Bearer {{auth}}

### Post move to game
POST {{endpoint}}/api/games/123-abc-123/moves HTTP/1.1
Content-type: application/json
X-MyChessAuth: Bearer {{auth}}

{
  "move": "A1A2",
  "comment": "Here we go!",
  "promotion": "Queen",
  "start": "2020-04-05T15:48:57.484Z",
  "end": "2020-04-05T15:49:05.000Z"
}
